# Generated by Django 5.2.7 on 2025-10-23 08:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+996', max_length=128, null=True, region=None),
        ),
    ]
