# Generated by Django 5.2.7 on 2025-10-21 14:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
