# Generated by Django 5.2.7 on 2025-10-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_app', '0002_product_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=1, upload_to='product_images'),
            preserve_default=False,
        ),
    ]
